namespace Brimma.LOSService.Config
{
    public class EncompassAPIs
    {
        public string APIServer { get; set; }
        public string Pipeline { get; set; }
        public string PipelineLimit { get; set; }
        public string PipelineCursor { get; set; }
        public string PipelineCreateCursor { get; set; }
        public string BatchUpdate { get; set; }
        public string RetrieveBatchUpdateStatus { get; set; }
        public string RetrieveLoan { get; set; }
        public string RetrieveLoanField { get; set; }
        public string RetrieveLoanDocuments { get; set; }
        public string RetrieveLoanUWConditions { get; set; }
        public string RetrieveLoanPreliminaryConditions { get; set; }
        public string RetrieveLoanWithSpecificEntities { get; set; }
        public string LockResource { get; set; }
        public string UnLockResource { get; set; }
        public string UpdateLoan { get; set; }
        public string CreateLoan { get; set; }
        public string RetrieveUserProfile { get; set; }
        public string CreateLoanInFolder { get; set; }
        public string CreateLoanInFolderAssignLO { get; set; }
        public string RetrieveTemplateFolders { get; set; }
        public string RetrieveTemplatesList { get; set; }
        public string RetrieveBusinessContacts { get; set; }
        public string RetrieveAllMilestoneFreeRoles { get; set; }
        public string AssignAssociate { get; set; }
        public string RetrieveStates { get; set; }
        public string SDKServer { get; set; }
        public string ApplyTemplate { get; set; }
        public string RetrieveCreditScore { get; set; }
        public string GetLoanProgramFolders { get; set; }
        public string GetLoanProgramTemplateSet { get; set; }
        public string GetLoanProgramTemplate { get; set; }
        public string GetLoanClosingCostFolders { get; set; }
        public string GetClosingCostTemplateSet { get; set; }
        public string GetClosingCostTemplate { get; set; }
        public string GetUsers { get; set; }
        public string PipelinePagination { get; set; }
        public string PipelineCursorV1 { get; set; }
        public string PipelineCreateCursorV1 { get; set; }
        public string GetLoanTemplateSet { get; set; }
        public string GetLoanTemplate { get; set; }
        public string OrderService { get; set; }
        public string ServiceTransaction { get; set; }
        public string CreateDocument { get; set; }
        public string CreateAttachment { get; set; }
        public string UpdateAttachment { get; set; }
        public string AssignAttachment { get; set; }
        public string LoanMetadata { get; set; }
        public string GetBorrower { get; set; }
        public string RetrieveDocumentAttachments { get; set; }
        public string DownloadAttachment { get; set; }
        public string UpdateDocument { get; set; }
        public string RetrieveDocuments { get; set; }
        public string DownloadOriginalAttachments { get; set; }
        public string RetrieveAttachment { get; set; }
        public string GetAttachmentURLToUpload { get; set; }
        public string CreateDocumentV3 { get; set; }
        public string AssignAndRemoveAttachment { get; set; }
        public string FailedWebhookEvents { get; set; }
        public string FieldReader { get; set; }
        public string GetWebhookSubscriptions { get; set; }
        public string CreateChangeWebHookSubscription { get; set; }
        public string RetrieveLoanAttachmentsV3 { get; set; }
        public string RetrieveDisclosureTracking2015Logs { get; set; }
        public string GetCanonicalNamesV3 { get; set; }
        public string RetrieveCustomDataObject { get; set; }
        public string GetRateLockRequests { get; set; }
        public string SubmitRateLockRequest { get; set; }
        public string RetrieveLoanInfoForQualifier { get; set; }
        public string RetrieveLoanQualifier { get; set; }
        public string GetMilestone { get; set; }
        public string UpdateLoanWithTemplate { get; set; }
        public string GetLoanAssociates { get; set; }
        public string RetrieveLoanWithSpecificEntitiesV2 { get; set; }
        public string RetrieveLoanV2 { get; set; }
        public string UpdateLoanV2 { get; set; }
        public string RetrieveLoanDataComparison { get; set; }
        public string RetrieveEFolderDocuments { get; set; }
        public string RetrieveAllAttachments { get; set; }
        public double HttpTimeout { get; set; }
        public string RetrieveBranchOrgInfo { get; set; }
        public int APITimeout { get; set; }
        public string RemoveAttachment { get; set; }
        public string RemoveAttachments { get; set; }
        public string CreateBusinessContact { get; set; }
        public string UpdateBusinessContact { get; set; }
        public string AssignAttachmentV3 { get; set; }
        public string UpdateAttachmentV3 { get; set; }
    }
}